Link prediction
will-gerard/yelp_research pull request #11
Opened 2018-03-23 02:28 UTC by will-gerard

2018-03-27 01:12 UTC, mzwong requested changes

2018-03-27 01:12 UTC, mzwong commented on scripts/link_prediction.py
> +		size = (10830, num_dimensions)
Probably shouldn't hard code # of nodes (10830). If we need to hard code a variable, at least make it a variable at the top of the script

2018-03-27 01:12 UTC, mzwong commented on scripts/link_prediction.py
> +			if node_index < num_nodes:
remove this check, no longer necessary

2018-03-27 01:12 UTC, mzwong commented on scripts/link_prediction.py
> +	size = (10830, 10830)
don't hardcode, use variable at the top

2018-03-27 01:12 UTC, mzwong commented on scripts/link_prediction.py
> +	for i in range(0, 10830):
same here

2018-03-27 01:12 UTC, mzwong commented on scripts/separate_edge_lists.py
> +	num_nodes = 34
Should this be a variable at the top?

2018-03-27 01:12 UTC, mzwong commented on scripts/link_prediction.py
> +		score = S[node1][node2]
all these subtract ones can be fixed if you subtract a variable from them. Set the variable up top like so:
```
ZERO_INDEXING_NODES = True
if ZERO_INDEXING_NODES:
  offset = 1
else:
  offset = 0
....
score = S[node1][node2] - offset

2018-03-27 01:12 UTC, mzwong commented on scripts/link_prediction.py
> +	'''
<nit> why are your tabs so big lmao? 8 spaces seems excessive but yolo go big or go home i guess

2018-03-27 01:12 UTC, mzwong commented on scripts/separate_edge_lists.py
> +	#TODO: check to make sure removing these edges leaves the graph connected
we need to decide how necessary it is to keep the graph connected

2018-04-03 16:14 UTC, will-gerard commented on scripts/link_prediction.py
> +	'''
Are those 8 spaces long on your computer? On mine they are 4 spaces.

2018-04-03 16:14 UTC, will-gerard commented on scripts/link_prediction.py
> +		size = (10830, num_dimensions)
Done

2018-04-03 16:14 UTC, will-gerard commented on scripts/link_prediction.py
> +			if node_index < num_nodes:
Done

2018-04-03 16:14 UTC, will-gerard commented on scripts/link_prediction.py
> +	size = (10830, 10830)
Done

2018-04-03 16:14 UTC, will-gerard commented on scripts/link_prediction.py
> +	for i in range(0, 10830):
Done

2018-04-03 16:14 UTC, will-gerard commented on scripts/link_prediction.py
> +		score = S[node1][node2]
Done

2018-04-03 16:14 UTC, will-gerard commented on scripts/separate_edge_lists.py
> +	num_nodes = 34
Changed to a mandatory parameter the function accepts

2018-04-09 03:31 UTC, mzwong approved these changes

2018-04-09 03:31 UTC, merged